#!/usr/bin/python
# -*- coding: utf-8 -*-
#File name: settingData.py
#Author: sanfanling
#licence: GPL-V3 


from configparser import ConfigParser
import os.path


class settingData:
    
    def __init__(self):
        self.fileName = os.path.expanduser("~/.foxGo2/foxGo2.conf")
        if not os.path.exists(self.fileName):
            self.initConfigfile()
    
    def getSettingData(self):
        self.cf = ConfigParser()
        self.cf.read(self.fileName)
        self.sgfPath = self.cf.get("general", "sgfpath")
        self.backgroundMusic = self.cf.getboolean("general", "backgroundmusic")
        self.musicPath = self.cf.get("general", "musicpath")
        self.effectSounds = self.cf.getboolean("general", "effectsounds")
        self.withCoordinate = self.cf.getboolean("board", "withcoordinate")
        self.stepsNumber = self.cf.get("board", "stepsnumber")
        self.boardStyle = self.cf.get("board", "boardstyle")
        self.hideCursor = self.cf.getboolean("board", "hidecusror")
        self.windowState = self.cf.get("session", "windowstate")
        
    
    def initConfigfile(self):
        configrations = """
        
        ### this file was generated by foxGo2 as its config file
        ### if any error occurs during parsing the config file
        ### please del this file and generate again
        ### because the application is being developed
        
        [general]
        sgfpath = ~/.foxGo2/sgf
        backgroundmusic = False
        musicpath = res/sounds/gsls.wav
        effectsounds = False
        
        [board]
        withcoordinate = True
        stepsnumber = hide
        boardstyle = style2
        hidecusror = False
        
        [session]
        windowstate = 
        
        """
        
        with open(self.fileName, "w") as f:
            f.write(configrations)
