#!/usr/bin/python
# -*- coding: utf-8 -*-
#File name: settingData.py
#Author: sanfanling
#licence: GPL-V3 


from configparser import ConfigParser
import os.path, pickle


class settingData:
    
    def __init__(self):
        self.fileName = os.path.expanduser("~/.foxGo2/foxGo2.conf")
        self.windowStateFileName = os.path.expanduser("~/.foxGo2/windowstate")
        if not os.path.exists(self.fileName):
            self.initConfigfile()
        if not os.path.exists(self.windowStateFileName):
            f = open(self.windowStateFileName, "wb")
            f.close()
    
    def getSettingData(self):
        self.cf = ConfigParser()
        self.cf.read(self.fileName)
        self.sgfPath = self.cf.get("general", "sgfpath")
        self.backgroundMusic = self.cf.getboolean("general", "backgroundmusic")
        self.musicPath = self.cf.get("general", "musicpath")
        self.effectSounds = self.cf.getboolean("general", "effectsounds")
        self.autoSkip = self.cf.getboolean("general", "autoskip")
        self.withCoordinate = self.cf.getboolean("board", "withcoordinate")
        self.stepsNumber = self.cf.get("board", "stepsnumber")
        self.boardStyle = self.cf.get("board", "boardstyle")
        self.hideCursor = self.cf.getboolean("board", "hidecursor")
        #self.windowState = self.cf.get("session", "windowstate")
        with open(self.windowStateFileName, "rb") as f:
            self.windowState = f.read()
    
    def setSettingData(self):
        self.cf.set("general", "sgfpath", str(self.sgfPath))
        self.cf.set("general", "backgroundmusic", str(self.backgroundMusic))
        self.cf.set("general", "musicpath", str(self.musicPath))
        self.cf.set("general", "effectsounds", str(self.effectSounds))
        self.cf.set("board", "withcoordinate", str(self.withCoordinate))
        self.cf.set("board", "stepsnumber", str(self.stepsNumber))
        self.cf.set("board", "boardstyle", str(self.boardStyle))
        self.cf.set("board", "hidecursor", str(self.hideCursor))
    
    def writeToFile(self):
        with open(self.fileName, "w") as f:
            self.cf.write(f)
        
        with open(self.windowStateFileName, "wb") as ff:
            ff.write(self.windowState)
        
    
    def initConfigfile(self):
        configrations = """
        
        ### this file was generated by foxGo2 as its config file
        ### if any error occurs during parsing the config file
        ### please del this file and generate again
        ### because the application is being developed
        
        [general]
        sgfpath = ~/.foxGo2/sgf
        backgroundmusic = False
        musicpath = res/sounds/gsls.wav
        effectsounds = False
        autoskip = True
        
        [board]
        withcoordinate = True
        stepsnumber = hide
        boardstyle = style2
        hidecursor = False
        """
        
        with open(self.fileName, "w") as f:
            f.write(configrations)
